default: &default
  adapter: postgresql
  encoding: utf8
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: spectre_development

test: &test
  <<: *default
  database: spectre_test

cucumber:
  <<: *test

production:
  <<: *default
  url: postgres://udktamttm:yQQhAGIxxwllXDJX@sst-pg10-ds1-1.cxjsifzx23qn.us-west-2.rds.amazonaws.com:5432/ds1vpszkfhn
